flaskapp/main/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flaskapp.models import User, Project, Group
from flaskapp.main.forms import LoginForm
from flask_login import login_user, logout_user, current_user, login_required
from flask_babel import gettext
import sys

main = Blueprint('main', __name__)


@main.route('/')
def home():
    if not current_user.is_anonymous and not current_user.is_admin:
        if current_user.group.is_containing_sections:
            group = current_user.group
        elif not current_user.group.is_containing_sections:
            section = User.query.filter_by(login=current_user.group.name).first()
            group = section.group
    else:
        group = None
    return render_template('home.html', title=gettext('Strona główna'), group=group)


@main.route('/about')
def about():
    return render_template('about.html')


@main.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(login=form.login.data).first()
        if user and user.is_admin:
            remember_me_value = int(form.remember.data == True)
            return redirect(url_for('admin.admin_login', admin_name=form.login.data, remember=remember_me_value))
        if user:
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            flash(gettext('Zalogowałeś się'), 'success')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash(gettext('Logowanie nieudane. Sprawdź poprawność wpisanych danych'), 'danger')

    return render_template('login.html', title=gettext('Zaloguj się'), form=form)


@main.route('/logout')
def logout():
    logout_user()
    flash(gettext('Wylogowałeś się'), 'success')
    return redirect(url_for('main.home'))


@main.route('/project/view', defaults={'section_id': None})
@main.route('/project/view/<int:section_id>')
@login_required
def project_view(section_id):
    if not current_user.is_admin and current_user.group.is_containing_sections:
        project = current_user.project
    elif not current_user.is_admin and not current_user.group.is_containing_sections:
        user = User.query.filter_by(login=current_user.group.name).first()
        project = user.project
    elif current_user.is_admin:
        project = Project.query.filter_by(user_id=section_id).first()
    group = project.author.group
    section_keys = [section.login for section in group.users]
    raters_pool_per_project_num = User.query.filter_by(did_rate=True, rating_type='pool_per_project').join(Group, Group.id == User.group_id).filter(Group.name.in_(section_keys), Group.name != project.author.login).count()
    if raters_pool_per_project_num == 0:
        raters_pool_per_project_num = 1

    return render_template('project_view.html', title=gettext('Projekt'), project=project, group=group, raters_pool_per_project_num=raters_pool_per_project_num)


@main.route('/results', defaults={'group_id': None})
@main.route('/results/<int:group_id>')
@login_required
def results(group_id):
    if current_user.is_admin:
        group = Group.query.get_or_404(group_id)
        user_project = None
    else:
        if current_user.group.is_containing_sections:
            group = current_user.group
            if current_user.project:
                user_project = current_user.project
            else:
                user_project = None
        else:
            section = User.query.filter_by(login=current_user.group.name).first()
            group = section.group
            if section.project:
                user_project = section.project
            else:
                user_project = None

    group_projects = Project.query.join(User).filter(User.group == group).order_by(User.section_number.asc()).all()

    section_keys = [section.login for section in group.users]
    users_that_rated_num = User.query.filter_by(did_rate=True).join(Group, Group.id == User.group_id).filter(Group.name.in_(section_keys)).count()

    evaluators_nums = dict()
    evaluators_nums['points_pool_evaluators'] = User.query.filter_by(did_rate=True, rating_type='points_pool').join(Group, Group.id == User.group_id).filter(Group.name.in_(section_keys)).count()
    evaluators_nums['points_pool_shuffled_evaluators'] = User.query.filter_by(did_rate=True, rating_type='points_pool_shuffled').join(Group, Group.id == User.group_id).filter(Group.name.in_(section_keys)).count()
    evaluators_nums['pool_per_project_evaluators'] = User.query.filter_by(did_rate=True, rating_type='pool_per_project').join(Group, Group.id == User.group_id).filter(Group.name.in_(section_keys)).count()

    # numbers needed to calculate score for 3 method
    raters_pool_per_project_nums = dict()
    for project in group_projects:
        raters_num_temp = User.query.filter_by(did_rate=True, rating_type='pool_per_project').join(Group, Group.id == User.group_id).filter(Group.name.in_(section_keys), Group.name != project.author.login).count()
        if raters_num_temp == 0:
            raters_num_temp = 1
        raters_pool_per_project_nums[project] = raters_num_temp

    # sorting for method 3 results
    group_projects_sorted = sorted(group_projects, key=lambda project: project.score_pool_per_project/(raters_pool_per_project_nums.get(project)), reverse=True)

    return render_template('results.html', title=gettext('Wyniki'), group=group, group_projects=group_projects,
                           group_projects_sorted=group_projects_sorted, user_project=user_project,
                           users_that_rated_num=users_that_rated_num, raters_pool_per_project_nums=raters_pool_per_project_nums, evaluators_nums=evaluators_nums)

flaskapp/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flaskapp import app, db
from flaskapp.models import User, Project, Group, Comments
from flaskapp.users.forms import CreateProjectForm, UpdateProjectForm, PointsForm
from flaskapp.main.forms import PointsPoolPerProjectForm
from flask_login import current_user, login_required
import os
from datetime import datetime
from flaskapp.users.utils import save_file, create_users_keys
import pytz
from flask_babel import gettext
from random import shuffle, choice

users = Blueprint('users', __name__)


@users.route('/project', methods=['GET', 'POST'])
@login_required
def project():
    if not current_user.is_admin and current_user.group.is_containing_sections:
        if not current_user.project and current_user.group.rating_status == 'disabled_improvement':
            flash(gettext('Teraz trwa poprawa projektów. Nie możesz poprawić projektu jeśli go wcześniej nie udostępniłeś.'), 'warning')
            return redirect(url_for('main.home'))
        if current_user.project:
            return redirect(url_for('main.project_view'))
        form = CreateProjectForm()
        group = current_user.group
        if form.validate_on_submit():
            if current_user.group.rating_status != 'disabled' and current_user.group.rating_status != 'disabled_improvement':
                return redirect(url_for('main.home'))
            new_file = save_file(form.file.data)

            ip = request.environ.get('HTTP_X_FORWARDED_FOR')
            if ip is None:
                ip = request.remote_addr

            if ip:
                user_ip = ip
            else:
                user_ip = None

            new_project = Project(title=form.title.data, description=form.description.data,
                                  upload_file=new_file, creators_num=form.creators_num.data,
                                  author=current_user, optional_link=form.url.data, last_editor=user_ip,
                                  date_posted=datetime.now(pytz.timezone('Poland')))
            db.session.add(new_project)
            db.session.commit()
            create_users_keys(current_user.login, form.creators_num.data)
            flash(gettext('Projekt został dodany'), 'success')
            return redirect(url_for('users.access_keys'))
    else:
        flash(gettext('Dostęp do tej strony posiada tylko sekcja'), 'warning')
        return redirect(url_for('main.home'))
    return render_template('project.html', title=gettext('Projekt'), form=form, legend=gettext('Dodaj projekt'), group=group)


@users.route('/project/update', methods=['GET', 'POST'])
@login_required
def update_project():
    if not current_user.is_admin:
        if not current_user.project and current_user.group.rating_status == 'disabled_improvement':
            flash(gettext('Teraz trwa poprawa projektów. Nie możesz poprawić projektu jeśli go wcześniej nie udostępniłeś.'), 'warning')
            return redirect(url_for('main.home'))
        if not current_user.project:
            return redirect(url_for('users.project'))
        form = UpdateProjectForm()
        user_project = Project.query.filter_by(author=current_user).first()
        group = user_project.author.group
        section_keys = [section.login for section in group.users]
        raters_pool_per_project_num = User.query.filter_by(did_rate=True, rating_type='pool_per_project').join(Group, Group.id == User.group_id).filter(Group.name.in_(section_keys), Group.name != user_project.author.login).count()
        if raters_pool_per_project_num == 0:
            raters_pool_per_project_num = 1

        if form.validate_on_submit():
            if current_user.group.rating_status != 'disabled' and current_user.group.rating_status != 'disabled_improvement':
                return redirect(url_for('main.home'))
            #####
            if group.rating_status == 'disabled':
                user_project.title = form.title.data
                user_project.description = form.description.data
                user_project.optional_link = form.url.data
                user_project.date_posted = datetime.now(pytz.timezone('Poland'))
            else:
                user_project.title_improvement = form.title.data
                user_project.description_improvement = form.description.data
                user_project.optional_link_improvement = form.url.data
                user_project.date_posted_improvement = datetime.now(pytz.timezone('Poland'))
            #####

            # get user IP
            ip = request.environ.get('HTTP_X_FORWARDED_FOR')
            if ip is None:
                ip = request.remote_addr

            if ip:
                user_ip = ip
            else:
                user_ip = None

            user_project.last_editor = user_ip

            if form.file.data:
                if group.rating_status == 'disabled':
                    old_file = user_project.upload_file
                    new_file = save_file(form.file.data)
                    user_project.upload_file = new_file
                    os.remove(os.path.join(app.root_path, 'static/projects', old_file))
                else:
                    old_file = user_project.upload_file_improvement
                    new_file = save_file(form.file.data)
                    user_project.upload_file_improvement = new_file
                    if old_file:
                        os.remove(os.path.join(app.root_path, 'static/projects', old_file))

            db.session.commit()
            flash(gettext('Projekt został edytowany'), 'success')
            return redirect(url_for('main.project_view'))
        elif request.method == 'GET':
            if user_project.upload_file_improvement and (group.rating_status == 'disabled_improvement' or group.rating_status == 'enabled_improvement' or group.rating_status == 'ended_improvement'):
                form.title.data = user_project.title_improvement
                form.description.data = user_project.description_improvement
                form.url.data = user_project.optional_link_improvement
            else:
                form.title.data = user_project.title
                form.description.data = user_project.description
                form.url.data = user_project.optional_link
    else:
        flash(gettext('Dostęp do tej strony posiada tylko sekcja'), 'warning')
        return redirect(url_for('admin.panel'))
    return render_template('project.html', title=gettext('Edytuj projekt'), form=form, legend=gettext('Edytuj projekt'),
                           group=group, project=user_project, raters_pool_per_project_num=raters_pool_per_project_num)


@users.route('/keys')
@login_required
def access_keys():
    if not current_user.is_admin and current_user.group.is_containing_sections:
        users_group = Group.query.filter_by(name=current_user.login).first()
        if users_group:
            keys = [user.login for user in users_group.users]
        else:
            keys = None
    else:
        flash(gettext('Dostęp do tej strony posiada tylko sekcja'), 'warning')
        return redirect(url_for('main.home'))
    return render_template('keys.html', title=gettext('Klucze dostępu'), keys=keys)


@users.route('/rating', methods=['GET', 'POST'])
@login_required
def rating():
    if not current_user.is_admin and not current_user.group.is_containing_sections:
        # choose random rating type for user
        if not current_user.rating_type:
            current_user.rating_type = choice(['points_pool', 'points_pool_shuffled', 'pool_per_project'])
            db.session.commit()

        section = User.query.filter_by(login=current_user.group.name).first()
        group = Group.query.get_or_404(section.group.id)

        group_projects = list()
        for section in group.users:
            section_project = Project.query.filter_by(author=section).first()
            if section_project and section_project.author.login != current_user.group.name:
                group_projects.append(section_project)
        if len(group_projects) == 0:
            flash(gettext('Za mało udostępnionych projektów, aby przeprowadzić ocenianie'), 'warning')
            return redirect(url_for('main.project_view'))
        user_ratings = [{'points': 0} for item in range(len(group_projects))]

        # for rating_type='pool_per_project' different form is created
        if current_user.rating_type == 'pool_per_project':
            form = PointsPoolPerProjectForm(all_points=user_ratings, points_per_project=group.points_per_project)
        else:
            form = PointsForm(all_points=user_ratings, points_per_user=group.points_per_user)

        # if rating_type for user is "points_pool_shuffled" then shuffle projects for rating
        if current_user.rating_type == "points_pool_shuffled":
            to_shuffle = list(zip(group_projects, form.all_points))
            shuffle(to_shuffle)
            group_projects, form.all_points = zip(*to_shuffle)

        # from validation
        if form.validate_on_submit():
            if current_user.did_rate or group.rating_status != 'enabled':
                return redirect(url_for('main.home'))

            if current_user.rating_type == "points_pool":
                for i, single_project in enumerate(group_projects):
                    single_project.score_points_pool = single_project.score_points_pool + form.all_points[i].data.get('points')
            elif current_user.rating_type == "points_pool_shuffled":
                for i, single_project in enumerate(group_projects):
                    single_project.score_points_pool_shuffled = single_project.score_points_pool_shuffled + form.all_points[i].data.get('points')
            else:
                for i, single_project in enumerate(group_projects):
                    single_project.score_pool_per_project += form.all_points[i].data.get('points')

flaskapp/templates/about.html
{% extends "layout.html" %}
{% block body %}
    <div class="jumbotron">
      <h1 class="display-4">{{ gettext('Aplikacja \'zapunktuj\'') }}</h1>
      <p class="lead">{{ gettext('Na tej stronie masz możliwość udostępnienia swojego projektu oraz oceny projektów udostępnionych przez innych użytkowników.') }}</p>
      <p class="lead">{{ gettext('Aplikacja została wykonana w ramach pracy dyplomowej.') }}</p>
      <hr class="my-4">
      <p>{{ gettext('Autor: Sebastian Kania') }}</p>
      <p>{{ gettext('Kontakt: zapunktuj.kontakt@gmail.com') }}</p>
    </div>
{% endblock body %}

flaskapp/templates/admin.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="" novalidate>
			{{ form.hidden_tag() }}
			<fieldset>

				<legend class="border-bottom">Utwórz grupę</legend>

				<div class="form-group">
					{{ form.name.label(class="form-control-label") }}

					{% if form.name.errors %}
						{{ form.name(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.name.errors %}
							<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.name(class="form-control form-control-lg") }}
					{% endif %}
				</div>

                <div class="form-group">
					{{ form.number.label(class="form-control-label") }}

					{% if form.number.errors %}
						{{ form.number(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.number.errors %}
							<span>{{ error }}</span>
							{% endfor %}
						</div>
					{% else %}
						{{ form.number(class="form-control form-control-lg") }}
					{% endif %}
				</div>

			</fieldset>

				<div class="form-group mt-3">
					{{ form.submit(class="btn btn-outline-info") }}
				</div>
		</form>
	</div>
{% endblock content%}

flaskapp/templates/home.html
{% extends "layout.html" %}
{% block body %}

    {% if current_user.is_anonymous %}
        <div class="jumbotron">
          <h1 class="display-4">{{ gettext('Witaj!') }}</h1>
          <p class="lead"> {{ gettext('Na tej stronie możesz udostępnić swój projekt oraz wziąć udział w ocenie projektów innych użytkowników.') }} </p>
          <hr class="my-4">
          <p>{{ gettext('Użyj klucza dostępu otrzymanego od nauczyciela, aby się zalogować.') }}</p>
          <a class="btn btn-primary btn-lg" href="{{ url_for('main.login') }}" role="button">{{ gettext('Zaloguj się') }}</a>
        </div>
    {% elif current_user.is_admin %}
        <div class="jumbotron">
          <h1 class="display-4">{{ gettext('Jesteś zalogowany jako administrator!') }}</h1>
          <p class="lead"> {{ gettext('Możesz tworzyć grupy projektowe oraz nimi zarządzać.') }} </p>
          <hr class="my-4">
          <p>{{ gettext('Aby zarządzać systemem przejdź do panelu administracyjnego.') }}</p>
          <a class="btn btn-primary btn-lg" href="{{ url_for('admin.panel') }}" role="button">{{ gettext('Panel') }}</a>
        </div>
    {% elif current_user.group.is_containing_sections %}
        <div class="jumbotron">
          <h1 class="display-4">{{ gettext('Witaj!') }}</h1>
          <p class="lead"> {{ gettext('Na tej stronie możesz udostępnić swój projekt oraz wziąć udział w ocenie projektów innych użytkowników.') }} </p>
          {% if current_user.group.upload_time %}
              <p class="lead"> {{ gettext('Termin na udostępnienie projektu:') }} <b> {{ current_user.group.upload_time.strftime('%d-%m-%Y, %H:%M') }} </b> </p>
          {% else %}
              <p class="lead"> {{ gettext('Termin na udostępnienie projektu:') }} <b> {{ gettext('nie wyznaczono') }} </b> </p>
          {% endif %}
          {% if current_user.group.rating_status == 'disabled_improvement' %}
            <p class="h3 text-primary"> {{ gettext('Możesz teraz poprawić swój projekt') }}. </p>
          {% endif %}
          <hr class="my-4">
          <p> {{ gettext('Jesteś zalogowany. Możesz udostępnić projekt lub go edytować.') }}</p>
          <a class="btn btn-primary btn-lg" href="{{ url_for('users.project') }}" role="button">{{ gettext('Projekt') }}</a>
        </div>
    {% elif not current_user.group.is_containing_sections %}
        <div class="jumbotron">
          <h1 class="display-4">{{ gettext('Witaj!') }}</h1>
          <p class="lead"> {{ gettext('Na tej stronie możesz udostępnić swój projekt oraz wziąć udział w ocenie projektów innych użytkowników.') }}</p>
          {% if group.rating_status == 'disabled_improvement' %}
            <p class="h3 text-primary"> {{ gettext('Możesz teraz poprawić swój projekt jeśli zalogujesz się jako sekcja (za pomocą pierwotnego klucza)') }}. </p>
          {% endif %}
          <hr class="my-4">
          <p> {{ gettext('Jesteś zalogowany. Możesz teraz ocenić projekty stworzone przez innych studentów lub zobaczyć wyniki końcowe.') }}</p>
          <a class="btn btn-primary btn-lg" href="{{ url_for('users.rating') }}" role="button">{{ gettext('Ocenianie') }}</a>
        </div>
    {% endif %}

{% endblock body %}

flaskapp/templates/keys.html
{% extends "layout_section.html" %}
{% block content %}

    {% if keys %}

        <div class="jumbotron">
          <h4>{{ gettext('Klucze dostępu') }}</h4>
          <hr class="my-4">
          <p class="lead">{{ gettext('Poniższe klucze służą do zalogowania się, aby ocenić projekty innych studentów') }}</p>
          <p class="lead">{{ gettext('Każda osoba z sekcji projektowej powinna użyć jednego z nich, kiedy rozpocznie się ocenianie') }}</p>
        </div>

        <table class="table table-hover text-center table-striped">
          <thead class="thead-dark">
            <tr>
              <th scope="col">{{ gettext('Nr.') }}</th>
              <th scope="col">{{ gettext('Klucz') }}</th>
            </tr>
          </thead>

          <tbody>
          {% for key in keys %}
            <tr>
              <th>{{ loop.index }}</th>
              <td>{{ key }}</td>
            </tr>
          {% endfor %}
          </tbody>

        </table>

    {% else %}
        <div class="jumbotron">
          <h4>{{ gettext('Klucze nie zostały jeszcze wygenerowane') }}</h4>
          <hr class="my-4">
          <p class="lead">{{ gettext('Zostaną one stworzone po udostępnieniu projektu') }}</p>
        </div>
    {% endif %}
{% endblock content %}

flaskapp/templates/layout.html
<!DOCTYPE html>
<html>
<head>
	 <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

	<link rel="stylesheet" type="text/css" href="{{url_for('static', filename='main.css')}}">

    <script src="https://kit.fontawesome.com/c1dc42c07b.js" crossorigin="anonymous"></script>

    <link rel="shortcut icon" href="{{ url_for('static', filename='logo.png') }}">

    {% if title %}
        <title>{{ title }}</title>
    {% else %}
        <title>zapunktuj</title>
    {% endif %}
</head>
<body>
	<header>
		<nav class="navbar navbar-dark bg-dark navbar-expand-md fixed-top">
			<div class="container">
				<a class="navbar-brand" href="{{ url_for('main.home') }}"><img src="{{url_for('static', filename='logo.png')}}" width="35" height="35" class="d-inline-block mr-2">{{ gettext('zapunktuj') }}
				</a>

				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#mainmenu" aria-controls="mainmenu" aria-expanded="false" aria-label="menu toggle">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div id="mainmenu" class="collapse navbar-collapse">

					<ul class="navbar-nav mr-auto">
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('main.home') }}">{{ gettext('Start') }}</a>
						</li>

						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('main.about') }}">{{ gettext('Informacje') }}</a>
						</li>
					</ul>

					<ul class="navbar-nav">
					{% if current_user.is_authenticated %}
						{% if current_user.is_admin %}
							<li class="nav-item">
								<a class="nav-item nav-link" href="{{ url_for('admin.panel') }}">{{ gettext('Panel Administratora') }}</a>
							</li>
						{% elif current_user.group.is_containing_sections %}
							<li class="nav-item">
								<a class="nav-item nav-link" href="{{ url_for('users.project') }}">{{ gettext('Projekt') }}</a>
							</li>
                        {% else %}
							<li class="nav-item">
								<a class="nav-item nav-link" href="{{ url_for('users.rating') }}">{{ gettext('Ocenianie') }}</a>
							</li>
						{% endif %}

						<li class="nav-item">
							<a class="nav-item nav-link" href="{{ url_for('main.logout') }}">{{ gettext('Wyloguj') }}</a>
						</li>
					{% else %}
						<li class="nav-item">
							<a class="nav-item nav-link" href="{{ url_for('main.login') }}">{{ gettext('Zaloguj') }}</a>
						</li>
					{% endif %}
					</ul>

				</div>
			</div>
		</nav>
	</header>

	<div class="container p-4">
		<div class="row">
			<div class="col-12">
			{% with messages=get_flashed_messages(with_categories=true) %}
				{% if messages %}
					{% for category, message in messages %}
						<div class="alert alert-{{ category }}">
							{{ message }}
						</div>
					{% endfor %}
				{% endif %}
			{% endwith %}
			{% block body %}{% endblock %}
			</div>
		</div>
	</div>

	<!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script type=text/javascript>
        $(function () {
          $('[data-toggle="tooltip"]').tooltip({
              delay: {
                  show: 600,
                  hide: 0
              }
          });
        })
    </script>

    {% block scripts %}{% endblock %}
</body>
</html>

flaskapp/templates/layout_project.html
{% extends "layout.html" %}
{% block body %}
<div class="row">
	<div class="col-md-3">
		<div class="body-section mr-5 pr-2">
			<h4>Menu</h4>
			<!--<p class='text-muted'>You can put any information here you'd like.-->
				<ul class="list-group">
					<a href="{{ url_for('project') }}" class="list-group-item list-group-item-light list-group-item-action">Dodaj Projekt</a>
					<a href="#" class="list-group-item list-group-item-light list-group-item-action">Edytuj Projekt</a>
					<a href="#" class="list-group-item list-group-item-light list-group-item-action">Ocenianie</a>
					<a href="#" class="list-group-item list-group-item-light list-group-item-action">Wyniki</a>
				</ul>
			<!--</p>-->
		</div>
	</div>

	<div class="col-md-8">
		{% block content %}{% endblock %}
	</div>
</div>
{% endblock body%}

flaskapp/templates/layout_section.html
{% extends "layout.html" %}
{% block body %}
<div class="row">
	<div class="col-md-3">
		<div class="body-section mr-5 mb-5 pr-2">
			<h4>{{ gettext('Menu') }}</h4>
            <ul class="list-group">
                {% if not current_user.project %}
                    <a href="{{ url_for('users.project') }}" class="list-group-item list-group-item-light list-group-item-action">{{ gettext('Dodaj Projekt') }}</a>
                {% else %}
                    <a href="{{ url_for('main.project_view') }}" class="list-group-item list-group-item-light list-group-item-action">{{ gettext('Podgląd Projektu') }}</a>
                    <a href="{{ url_for('users.update_project') }}" class="list-group-item list-group-item-light list-group-item-action">{{ gettext('Edytuj Projekt') }}</a>
                {% endif %}
                <a href="{{ url_for('users.access_keys') }}" class="list-group-item list-group-item-light list-group-item-action">{{ gettext('Klucze Do Oceniania') }}</a>
                <a href="{{ url_for('main.results') }}" class="list-group-item list-group-item-light list-group-item-action">{{ gettext('Wyniki') }}</a>
            </ul>
		</div>
	</div>

	<div class="col-md-9">
		{% block content %}{% endblock %}
	</div>
</div>
{% endblock body%}

flaskapp/templates/layout_user.html
{% extends "layout.html" %}
{% block body %}
<div class="row">
	<div class="col-md-3">
		<div id="user-menu">
			<div class="body-section mr-5 mb-5 pr-2">
				<h4>{{ gettext('Menu') }}</h4>
				<ul class="list-group">
					<a href="{{ url_for('main.project_view') }}" class="list-group-item list-group-item-light list-group-item-action">{{ gettext('Podgląd Projektu') }}</a>
					<a href="{{ url_for('users.rating') }}" class="list-group-item list-group-item-light list-group-item-action">{{ gettext('Oceń Projekty') }}</a>
					<a href="{{ url_for('main.results') }} " class="list-group-item list-group-item-light list-group-item-action">{{ gettext('Wyniki Końcowe') }}</a>
				</ul>
				<div class="sum text-center mt-4">
					<output class="output-text"></output>
					<output class="result"></output>
				</div>
			</div>
		</div>
	</div>

	<div class="col-md-9">
		{% block content %}{% endblock %}
	</div>
</div>
{% endblock body %}